site_name: biogather
site_description: Library to facilitate extraction of information from text and other modalities. Part of the BioCypher ecosystem.
site_author: Sebastian Lobentanzer
site_url: https://biocypher.github.io/biogather/

nav:
  - Home: index.md

  - About:
      - Project: about/project.md
      - Design philosophy: about/design-philosophy.md
      - Use Cases: about/use-cases.md

  - Get Started:
      - Installation: installation.md
      - Quickstart: learn/quickstart.md

  - Learn:
      - Tutorials:
          - Basics: learn/tutorials/basics.md

      - HowTo / FAQ:
          - learn/guides/index.md

  - Reference:
      - Reference Index: reference/index.md


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_submodules: true
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
      default_handler: python

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/biocypher
      name: Sebastian Lobentanzer

copyright: Copyright &copy 2025 Sebastian Lobentanzer

repo_url: https://github.com/biocypher/biogather
repo_name: biocypher/biogather

watch:
  - src/biogather
